### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by genisis1234r** [SilentChaos512/ScalingHealth#165] opened 2019-04-07 06:50 UTC
Scaling health Version 1.3.33
Silent Lib version 3.0.13
Forge Version 14.23.5.2778

On startup, on entering phase two of loading mods, once it gets to scaling health, it crashes.
Pastebin: https://pastebin.com/hC7VTRtv

**Comment by SilentChaos512** [comment] 2019-04-07 14:28
Duplicate of #161. You can either update Forge to latest, or downgrade Scaling Health.
(edit) Minimum version is 2779.

**Closed as completed** 2019-04-27 21:09 UTC
Labels: 1.12
