### ISSUE TITLE
Character Health Carries Between Worlds

### ISSUE THREAD

**Issue by Alaberti** [SilentChaos512/ScalingHealth#3] opened 2016-08-06 03:07 UTC
If you increase your health with the heart canisters in one world and go to another, the health increase carries over. I'm thinking that's not intended.

**Comment by SilentChaos512** [comment] 2016-08-06 05:10
Definitely not intended... Hilarious, but not intended.

**Comment by SilentChaos512** [comment] 2016-08-08 06:34
Can't reproduce in 0.2.0, so I'm guessing this is fixed by the new save system.

**Closed by SilentChaos512** 2016-08-08 06:34 UTC
Labels: bug
