### ISSUE TITLE
Crash w/ IgniteHUD

### ISSUE THREAD

**Issue by Preminenc3** [SilentChaos512/ScalingHealth#143] opened 2018-11-08 16:31 UTC
### Versions

Minecraft Version: 1.12.2
Scaling Health Version: ScalingHealth-1.12.2-1.3.31-132.jar
Silent Lib Version: SilentLib-1.12.2-3.0.8-158.jar

### Expected behavior

- Does not crash upon survival startup and when changing from creative to survival game mode

### Actual behaviour

- Game crashes when changing from creative to survival, when entering a survival world, or when creating a new survival world and entering it. It crashes when Ignite HUD is installed

### Steps to Reproduce the Problem

1. Install Scaling Health, SilentLib and Ignite HUD
2. launch the game in survival mode
3. wait for it to load
4. CTD!

[crash-2018-11-08_10.23.23-client.txt](https://github.com/SilentChaos512/ScalingHealth/files/2562585/crash-2018-11-08_10.23.23-client.txt)

**Comment by SilentChaos512** [comment] 2018-11-08 20:29
Duplicate of #140, nothing I can really do about it. Should already be reported to Ignite HUD.

**Closed as completed** 2019-02-16 23:48 UTC
Labels: wontfix
