### ISSUE TITLE
Infinite Atlas Stiching, this mod may be the issue ?

### ISSUE THREAD

**Issue by ZR-00** [SilentChaos512/ScalingHealth#264] opened 2020-05-02 00:47 UTC
I can easily recreate this bug, almost 100% will happen all the time.
the bug is encountered when "scaling health" installed while having a resource pack on.

if i want to play it, i must remove my resouce pack from the folder and then put ii back after it started
![Untitled](https://user-images.githubusercontent.com/64331654/80850962-effb9e00-8c48-11ea-8a11-913db22ffbb7.png)

**Comment by Cyborgmas** [comment] 2020-05-02 12:29
There is a bug report template for a reason, please provide all the information that was asked. (All the versions + log files)

**Comment by Cyborgmas** [comment] 2020-05-06 10:34
Labelling this one as duplicate of #266 even though it was opened before since there is much less information. The only thing I would like now are the logs (see #266 for how to give them to me) and also the mc version number to know if this happens also in 1.14.4

**Closed as completed** 2020-06-07 14:55 UTC
Labels: bug, duplicate
