### ISSUE TITLE
Limited Health

### ISSUE THREAD

**Issue by WenXin20** [SilentChaos512/ScalingHealth#4] opened 2016-08-07 00:05 UTC
With the limited Health option, going into the nether resets you back to having full health.

**Comment by SilentChaos512** [comment] 2016-08-07 04:46
This might get fixed by the new save system I'm finishing up. It will be in version 0.2.0. Let me know if the issue persists after the next update (should be out in a day or two).

**Comment by WenXin20** [comment] 2016-08-07 14:43
Ok

**Comment by SilentChaos512** [comment] 2016-08-08 06:11
Reproduced in 0.2.0. Player health is not actually changed, it's a desync issue. Difficult Life had the same bug. Funnily enough, that bug was the reason I created Health Bar...
![2016-08-08_01 05 56](https://cloud.githubusercontent.com/assets/5721949/17470796/dfcbfca4-5d04-11e6-931c-5e21cf6ecedc.png)

**Comment by WenXin20** [comment] 2016-08-08 14:42
Ok, is it fixable?

**Comment by SilentChaos512** [comment] 2016-08-08 18:11
Yes, definitely.

**Comment by WenXin20** [comment] 2016-08-08 18:43
Ok, cool, thanks

**Closed** 2016-08-08 19:27 UTC
Labels: bug
