### ISSUE TITLE
Medkit and Bandage does nothing

### ISSUE THREAD

**Issue by ZR-00** [SilentChaos512/ScalingHealth#267] opened 2020-05-07 07:45 UTC
## Versions

- **Scaling Health**: x.x.x
- **Silent Lib**: x.x.x
- **Forge**: x.x.x
- **Modpack**: N/A 
- **Optifine Installed**: No 

## Expected Behavior

giving healing buff or something when holding right click with item for 5 second
(Description here)

## Actual Behavior

tried holding right click does nothing, even when ur doing exactly 5 second. i even tried to even hold for 1 minute (putting my character in a berry bush helps keeping health low) and get out of the bush... and let go of the right click. still nothing.

tried both of em, bandages orr medkit, nothing. just nothing, both waste of space and resources.

and... its not even registered as a proper item when you hover ur mouse over it

## Links/Images

- (Link or file)
![2020-05-07_14 19 32](https://user-images.githubusercontent.com/64331654/81267301-6e54a780-9070-11ea-9ae5-9822a38f05e2.png)
![2020-05-07_14 19 31](https://user-images.githubusercontent.com/64331654/81267314-73b1f200-9070-11ea-9624-be3ed72f41f4.png)

- (Another link or file, if needed)

## Steps to Reproduce the Problem

1.
2.
3.

**Comment by Cyborgmas** [comment] 2020-05-15 13:15
I am unable to reproduce this. Could you confirm that you are on the latest version ? Also try to use the item only with SH installed and no other. For the missing translation i fixed it.

**Comment by Cyborgmas** [comment] 2020-05-31 13:25
If you do not provide more information I will be closing the issue as I can't reproduce it

**Closed as completed** 2020-07-01 00:18 UTC
Labels: bug, 1.15
