### ISSUE TITLE
Power Crystals not able to be consumed

### ISSUE THREAD

**Issue by 068151** [SilentChaos512/ScalingHealth#262] opened 2020-04-30 16:22 UTC
## Versions

- **Scaling Health**: 1.15.2
- **Silent Lib**: SilentLib-1.15.2-4.6.0+48.jar
- **Forge**: forge-1.15.2-31.1.49
- **Modpack**: Movement Modpack
- **Optifine Installed**: No

## Expected Behavior
Crystal being consumed

(Description here)

## Actual Behavior
Crystal is not consumed and no bonus to attack damage is applied

(Description here)

## Steps to Reproduce the Problem

1. Get Power Crystal
2. Try to use Power Crystal
3.

**Comment by Cyborgmas** [comment] 2020-04-30 21:42
You left out which version of 1.15.2 SH you are on. Are you on 3.0.5? (the latest right now)

**Comment by Qsandas** [comment] 2020-05-04 02:11
Possibly related? I know bugs can sometimes jump versions and re-emerge.
https://github.com/SilentChaos512/ScalingHealth/issues/245
I'll see if I can reproduce it to help out (I need to update anyways, so I might as well check each version along the way)
Edit: Unfortunately I was unable to reproduce the bug, Perhaps they just didn't have enough levels to use the crystal?

**Comment by Cyborgmas** [comment] 2020-05-04 11:01
Yeah that is what is weird. Thought of the previous bug in 1.14 and thought I would have fixed for 1.15 as well. Asked them their version but no response, will not be able to do more until they respond, thanks for the help though, greatly appreciated.

**Comment by Cyborgmas** [comment] 2020-05-31 13:24
If you can not provide more information I will be closing the issue as I can't reproduce it

**Closed as completed** 2020-07-01 00:18 UTC
Labels: bug, 1.15
